import 'package:get/get.dart';
import '../../data/repositories/order_repository.dart';
import '../../data/models/order_model.dart';
import '../../data/models/address_model.dart';
import '../cart/cart_controller.dart';
import '../auth/auth_controller.dart';
import '../address/address_controller.dart';
import '../notification/notification_controller.dart';
import '../../data/models/notification_model.dart';
import '../../data/repositories/notification_repository.dart';
import '../../app/routes/app_routes.dart';
import '../../core/utils/app_utils.dart';

class CheckoutController extends GetxController {
  final OrderRepository _orderRepo = Get.find<OrderRepository>();
  final CartController cartController = Get.find<CartController>();
  final AddressController addressController = Get.find<AddressController>();
  final AuthController auth = AuthController.instance;

  final RxBool isPlacingOrder = false.obs;
  final RxString paymentMethod = 'cash_on_delivery'.obs;

  Future<void> placeOrder() async {
    if (isPlacingOrder.value) return;

    final user = auth.firebaseUser.value;
    if (user == null) {
      AppUtils.showSnackbar(
        'Error',
        'You must be logged in to place an order.',
        isError: true,
      );
      return;
    }

    final AddressModel? address = addressController.selectedAddress.value;
    if (address == null) {
      AppUtils.showSnackbar(
        'Address Required',
        'Please select a delivery address.',
        isError: true,
      );
      return;
    }

    if (cartController.cartItems.isEmpty) {
      AppUtils.showSnackbar('Empty Cart', 'Your cart is empty.', isError: true);
      return;
    }

    try {
      isPlacingOrder.value = true;

      final orderItems = cartController.cartItems
          .map(
            (item) => OrderItemModel(
              productId: item.productId,
              title: item.title,
              thumbnail: item.thumbnail,
              price: item.price,
              quantity: item.quantity,
            ),
          )
          .toList();

      final newOrder = OrderModel(
        id: '', // Generated by Firestore
        userId: user.uid,
        items: orderItems,
        shippingAddress: address,
        subtotal: cartController.subtotal,
        deliveryFee: cartController.deliveryFee,
        total: cartController.total,
        paymentMethod: paymentMethod.value,
        paymentStatus: 'pending',
        orderStatus: 'placed',
      );

      final orderId = await _orderRepo.createOrder(newOrder);

      // Attempt to create notification
      try {
        if (Get.isRegistered<NotificationController>()) {
          final notifRepo = Get.find<NotificationController>();
          notifRepo
              .notifications; // Just to make sure it's alive, wait we should use repo
        }

        // Actually, let's just use the repo directly if needed, but it's cleaner to use repo directly
        final notifModel = NotificationModel(
          id: '',
          title: 'Order Placed 🎉',
          message: 'Your order #$orderId has been placed successfully.',
          type: 'order_placed',
          orderId: orderId,
          isRead: false,
        );
        // We know we can just inject NotificationRepository here or we can just let Firebase add it
        // Since we are in controller layer, let's fetch repository
        final notifRepo = Get.find<NotificationRepository>();
        await notifRepo.createNotification(notifModel);
      } catch (e) {
        // Silently fail notification, don't break order
      }

      // Order created successfully, now clear the cart
      await cartController.clearCart();

      // Navigate to success
      Get.offAllNamed(AppRoutes.orderSuccess, arguments: {'orderId': orderId});
    } catch (e) {
      AppUtils.showSnackbar(
        'Error',
        'Failed to place order. Please try again.',
        isError: true,
      );
    } finally {
      isPlacingOrder.value = false;
    }
  }
}
