// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuIBVVPngonbg_rlPqxi5zOYlpB5gNruI',
    appId: '1:211107409321:web:21914ee950f1f088ed28b8',
    messagingSenderId: '211107409321',
    projectId: 'shopora-2864c',
    authDomain: 'shopora-2864c.firebaseapp.com',
    storageBucket: 'shopora-2864c.firebasestorage.app',
    measurementId: 'G-QML8JS4VZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Q28m9VpjAj_mwANfrlxqGxRXYeb2iKw',
    appId: '1:211107409321:android:a365cb4a3ca6bd50ed28b8',
    messagingSenderId: '211107409321',
    projectId: 'shopora-2864c',
    storageBucket: 'shopora-2864c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCWgEGrglReMHQmYnFUvlMkjo31svcrnM',
    appId: '1:211107409321:ios:357fb96ed6d1b6ceed28b8',
    messagingSenderId: '211107409321',
    projectId: 'shopora-2864c',
    storageBucket: 'shopora-2864c.firebasestorage.app',
    iosBundleId: 'com.example.cartly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCWgEGrglReMHQmYnFUvlMkjo31svcrnM',
    appId: '1:211107409321:ios:357fb96ed6d1b6ceed28b8',
    messagingSenderId: '211107409321',
    projectId: 'shopora-2864c',
    storageBucket: 'shopora-2864c.firebasestorage.app',
    iosBundleId: 'com.example.cartly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuIBVVPngonbg_rlPqxi5zOYlpB5gNruI',
    appId: '1:211107409321:web:f25d62d6f8d332c7ed28b8',
    messagingSenderId: '211107409321',
    projectId: 'shopora-2864c',
    authDomain: 'shopora-2864c.firebaseapp.com',
    storageBucket: 'shopora-2864c.firebasestorage.app',
    measurementId: 'G-X5ES5ZZB5Z',
  );
}
